name: Build ASP.NET

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check current location
        run: |
          pwd
          ls -la

      - name: Install .NET SDK
        run: |
          echo "Ensure dotnet CLI is available"
          dotnet --version

      - name: Restore dependencies
        run: dotnet restore


      - name: Build
        run: dotnet build --configuration Release
