name: Local Gitea CI (No Checkout Folder)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      - name: Check .NET Version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore $GITHUB_WORKSPACE/DriverNextJS.sln

      - name: Test project
        run: dotnet test $GITHUB_WORKSPACE/DriverNextJS.sln --configuration Release

      - name: Publish Backend
        run: |
          cd backend
          dotnet publish -c Release -o publish

      # ... previous steps ...

      - name: Install SMB Client
        run: sudo apt-get update && sudo apt-get install -y smbclient

      - name: Deploy Backend to Windows Share
        run: |
          # Navigate to publish folder
          cd backend/publish
          
          # Connect to Windows and upload files recursively
          # Syntax: smbclient //IP/Share -U "User%Password" -c "commands"
          smbclient '//${{ secrets.WIN_IP }}/${{ secrets.WIN_SHARE_NAME }}' \
            -U '${{ secrets.WIN_USER }}%${{ secrets.LAN_PASS }}' \
            -c 'prompt OFF; recurse ON; mput *'

      - name: Create .env file for Next.js
        run: |
          cd frontend
          echo "NEXT_PUBLIC_PROD_API_LINK=${{ secrets.NEXT_PUBLIC_PROD_API_LINK }}" >> .env
          echo "NEXT_PUBLIC_PROD_LOGIN_LINK=${{ secrets.NEXT_PUBLIC_PROD_LOGIN_LINK }}" >> .env
          echo "NEXT_PUBLIC_PROD_SERVICE_LINK=${{ secrets.NEXT_PUBLIC_PROD_SERVICE_LINK }}" >> .env

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Build Next.js
        run: cd frontend && npm run build
