name: Local Gitea CI (No Checkout Folder)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Show workspace path and files
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      # 2. Install .NET SDK (check version)
      - name: Install .NET SDK
        run: dotnet --version

      # 3. Restore NuGet dependencies
      - name: Restore dependencies
        run: dotnet restore $GITHUB_WORKSPACE/DriverNextJS.sln

      # 4. Build ASP.NET project
      - name: Build project
        run: dotnet test $GITHUB_WORKSPACE/DriverNextJS.sln --configuration Release

      # 5. Build ASP.NET project
      - name: Build project
        run: cd backend && dotnet publish -c Release -o \\\\172.20.5.34\\wwwroot\\DriverApi

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_PROD_API_LINK=${{ secrets.NEXT_PUBLIC_PROD_API_LINK }}" > .env
          echo "NEXT_PUBLIC_PROD_LOGIN_LINK=${{ secrets.NEXT_PUBLIC_PROD_LOGIN_LINK }}" > .env
          echo "NEXT_PUBLIC_PROD_SERVICE_LINK=${{ secrets.NEXT_PUBLIC_PROD_SERVICE_LINK }}" > .env


      # 6. Publish Project NextJS + ASP.NET
      - name: npm install
        run: cd frontend && npm install

      # 7. Publish Project NextJS + ASP.NET
      - name: npm publish
        run: cd frontend && npm run build
