name: Local Gitea CI (HTTP Clone)

on:
  push:
    branches:
      - Feature             # trigger workflow when pushing to v3 branch
  workflow_dispatch:  # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest  # or your self-hosted runner

    steps:
      # 1. Clone repository via HTTP using PAT
      - name: Clone Gitea repo via HTTP
        run: |
          git clone http://20234111:${{ secrets.PAT }}@156.71.5.100:3000/20234111/checkout.git
          cd checkout
          git checkout v3
          echo "Files in repo after checkout:"
          ls -la

      # 2. Install .NET SDK (ensure dotnet CLI is available)
      - name: Install .NET SDK
        run: dotnet --version

      # 3. Restore NuGet dependencies
      - name: Restore dependencies
        run: |
          cd checkout
          dotnet restore

      # 4. Build ASP.NET project
      - name: Build project
        run: |
          cd checkout
          dotnet build --configuration Release
