# name: Build ASP.NET

# on:
#   [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: 20234111/checkout@v3

#       - name: Install .NET SDK
#         run: |
#           echo "Ensure dotnet CLI is available"
#           dotnet --version

#       - name: Restore dependencies
#         run: dotnet restore


#       - name: Build
#         run: dotnet build --configuration Release


name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print contexts
        run: |
          echo "github.repository=${{ github.repository }}"
          echo "gitea.repository=${{ gitea.repository }}"
          echo "vars.CHECKOUTREPO=${{ vars.CHECKOUTREPO }}"
          echo "vars.SHA=${{ vars.SHA }}"
      - name: Clone repository from local Gitea
        run: |
          echo "Cloning from local server..."
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -t ed25519 156.71.5.100 >> ~/.ssh/known_hosts
          git clone gitea@156.71.5.100:${{ vars.CHECKOUTREPO }}.git .
          git checkout ${{ vars.SHA }}
          echo "Files checked out:"
          ls -la

      - name: Setup environment
        run: |
          echo "Node version: $(node --version)"
          echo "Dotnet version: $(dotnet --version)"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # - name: Test
      #   run: dotnet test --configuration Release --no-build

      - name: Publish
        run: dotnet publish --configuration Release --no-build -o ./publish

      - name: Show results
        run: |
          echo "Build artifacts:"
          ls -la ./publish