name: Local Gitea CI (No Checkout Folder)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Show workspace path and files
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      # 2. Install .NET SDK (check version)
      - name: Install .NET SDK
        run: dotnet --version

      # 3. Restore NuGet dependencies
      - name: Restore dependencies
        run: dotnet restore $GITHUB_WORKSPACE/DriverNextJS.sln

      # 4. Build ASP.NET project
      - name: Build project
        run: dotnet test $GITHUB_WORKSPACE/DriverNextJS.sln --configuration Release

      # 5. Publish Project NextJS + ASP.NET
      - name: NPM Install
        run: cd frontend && npm install

      # 5. Publish Project NextJS + ASP.NET
      - name: NPM Publish
        run: npm run publish
