name: Local Gitea CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_PROD_API_LINK=${{ secrets.NEXT_PUBLIC_PROD_API_LINK }}" > frontend/.env
          echo "NEXT_PUBLIC_PROD_LOGIN_LINK=${{ secrets.NEXT_PUBLIC_PROD_LOGIN_LINK }}" >> frontend/.env
          echo "NEXT_PUBLIC_PROD_SERVICE_LINK=${{ secrets.NEXT_PUBLIC_PROD_SERVICE_LINK }}" >> frontend/.env

      - name: Stop & remove Docker container
        run: docker-compose down -v

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker container
        run: docker-compose up -d 

      - name: Check container is running
        run: docker ps | grep driver_api

      - name: Show container logs
        run: docker logs driver_api
