# name: Build ASP.NET

# on:
#   [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: 20234111/checkout@v3

#       - name: Install .NET SDK
#         run: |
#           echo "Ensure dotnet CLI is available"
#           dotnet --version

#       - name: Restore dependencies
#         run: dotnet restore


#       - name: Build
#         run: dotnet build --configuration Release

name: Local Gitea CI

on:
  push:
    branches:
      - Feature
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   # or self-hosted runner

    steps:
      # 1. Checkout your Gitea repo using official checkout action
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 156.71.5.100 >> ~/.ssh/known_hosts

      - name: Clone Gitea repo
        run: |
          git clone git@156.71.5.100:20234111/checkout.git
          cd checkout
          git checkout Feature
          ls -la

      # 2. List files to confirm checkout
      - name: List repository files
        run: ls -la

      # 3. Restore and build ASP.NET project
      - name: Install .NET SDK
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release
