name: Local Gitea CI (No Checkout Folder)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      - name: Check .NET Version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore $GITHUB_WORKSPACE/DriverNextJS.sln

      - name: Test project
        run: dotnet test $GITHUB_WORKSPACE/DriverNextJS.sln --configuration Release

      - name: Publish Backend
        run: |
          cd backend
          dotnet publish -c Release -o publish

      - name: Mount LAN folder
        run: |
          sudo mkdir -p /mnt/driverapi
          sudo mount -t cifs //172.20.5.34/wwwroot/DriverApi /mnt/driverapi \
            -o username=${{ secrets.LAN_USER }},password=${{ secrets.LAN_PASS }},rw,uid=$(id -u),gid=$(id -g)

      - name: Copy files to LAN
        run: |
          sudo cp -r backend/publish/* /mnt/driverapi

      - name: Unmount
        run: sudo umount /mnt/driverapi

      - name: Create .env file for Next.js
        run: |
          cd frontend
          echo "NEXT_PUBLIC_PROD_API_LINK=${{ secrets.NEXT_PUBLIC_PROD_API_LINK }}" >> .env
          echo "NEXT_PUBLIC_PROD_LOGIN_LINK=${{ secrets.NEXT_PUBLIC_PROD_LOGIN_LINK }}" >> .env
          echo "NEXT_PUBLIC_PROD_SERVICE_LINK=${{ secrets.NEXT_PUBLIC_PROD_SERVICE_LINK }}" >> .env

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Build Next.js
        run: cd frontend && npm run build
