# name: Build ASP.NET

# on:
#   [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: 20234111/checkout@v3

#       - name: Install .NET SDK
#         run: |
#           echo "Ensure dotnet CLI is available"
#           dotnet --version

#       - name: Restore dependencies
#         run: dotnet restore


#       - name: Build
#         run: dotnet build --configuration Release


name: Local Gitea CI

on:
  push:
    branches:
      - Feature          # trigger workflow on pushes to Feature
  workflow_dispatch:     # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest   # your local runner

    steps:
      # 1. Checkout repository from Gitea
      - name: Checkout local Gitea repo
        uses: actions/checkout@v3
        with:
          repository: 20234111/checkout   # your Gitea username/org + repo
          ref: Feature                     # branch to checkout
          token: ${{ secrets.PAT }} # Gitea personal access token
          persist-credentials: false       # do not overwrite Git credentials

      # 2. Verify files are present
      - name: List repository files
        run: |
          echo "Files in repo:"
          ls -la

      # 3. Example build step
      - name: Build project
        run: |
          echo "Add your build commands here"
          # e.g., dotnet build, npm install, etc.
