name: Local Gitea CI (Use Existing Repo)

on:
  push:
    branches:
      - Feature  # trigger workflow when pushing to Feature branch
  workflow_dispatch:  # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest  # or your self-hosted runner
    #update
    steps:
      # 1. Use existing checkout folder
      - name: Use existing repository
        run: |
          if [ ! -d "checkout" ]; then
            echo "Error: 'checkout' folder does not exist!"
            exit 1
          fi
          cd checkout
          echo "Files in repo:"
          ls -la

      # 2. Install .NET SDK (check version)
      - name: Install .NET SDK
        run: dotnet --version

      # 3. Restore NuGet dependencies
      - name: Restore dependencies
        run: |
          cd checkout
          dotnet restore

      # 4. Build ASP.NET project
      - name: Build project
        run: |
          cd checkout
          dotnet build --configuration Release
